---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if python installed
      raw: test -e /usr/bin/python
      register: python_installed
      failed_when: false
      changed_when: false
    - name: Install python for Ansible
      raw: apt update -y && apt install -y python-minimal
      when: python_installed.rc != 0
